[tool.bumpversion]
current_version = "1.0.0"

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = ".github/ISSUE_TEMPLATE/bug_report.yml"
search = """
      description: What version of **row** are you using?
      placeholder: {current_version}"""

replace = """
      description: What version of **row** are you using?
      placeholder: {new_version}"""

[[tool.bumpversion.files]]
filename = ".github/ISSUE_TEMPLATE/release.md"
search = "Release {current_version}"
replace = "Release {new_version}"

[[tool.bumpversion.files]]
filename = "doc/src/release-notes.md"
regex = true
search = 'Next release$'
replace = '{new_version} ({now:%Y-%m-%d})'
