ci:
  autoupdate_schedule: quarterly
  autoupdate_branch: 'trunk'
  autofix_prs: false

repos:
- repo: https://github.com/backplane/pre-commit-rust-hooks
  rev: v1.1.0
  hooks:
  - id: fmt
  - id: check
  - id: clippy
    args:
      - --all-targets
      - --all-features
      - --
      - -Dwarnings
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.5.0'
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: check-case-conflict
  - id: mixed-line-ending
- repo: https://github.com/rhysd/actionlint
  rev: v1.6.27
  hooks:
    - id: actionlint
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.3.4'
  hooks:
  - id: ruff-format
  - id: ruff

# TODO: add fix-license-header
