ci:
  autoupdate_schedule: quarterly
  autoupdate_branch: 'trunk'
  autofix_prs: false

repos:
- repo: https://github.com/backplane/pre-commit-rust-hooks
  rev: v1.1.0
  hooks:
  - id: fmt
  - id: check
  - id: clippy
    args:
      - --all-targets
      - --all-features
      - --
      - -Dwarnings
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.5.0'
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: check-case-conflict
  - id: mixed-line-ending
- repo: https://github.com/rhysd/actionlint
  rev: v1.6.27
  hooks:
    - id: actionlint
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.3.4'
  hooks:
  - id: ruff-format
  - id: ruff
- repo: https://github.com/glotzerlab/fix-license-header
  rev: v0.3.2
  hooks:
  - id: fix-license-header
    name: Fix license headers (rust)
    types_or: [rust]
    args:
    - --license-file=LICENSE
    - --add=Part of row, released under the BSD 3-Clause License.
    - --comment-prefix=//
- repo: https://github.com/crate-ci/typos
  rev: v1.21.0
  hooks:
    - id: typos
