version: 2
build:
  os: "ubuntu-22.04"
  commands:
    - mkdir -p bin
    - curl -sSL "https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz" | tar -xvz --directory "bin"
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - echo "site-url = \"/$READTHEDOCS_LANGUAGE/$READTHEDOCS_VERSION/\"" >> doc/book.toml
    - bin/mdbook build doc --dest-dir=$READTHEDOCS_OUTPUT/html
