version: 2
build:
  os: "ubuntu-24.04"
  tools:
    rust: "1.86"
  commands:
    # Install cargo binstall
    - mkdir -p "${PATH%%:*}"
    - curl -sSL "https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-gnu.tgz" | tar -xvz --directory "${PATH%%:*}"
    # Install mdbook
    - cargo binstall mdbook@0.5.0 --no-confirm --install-path "${PATH%%:*}"
    # Build the book
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - echo "site-url = \"/$READTHEDOCS_LANGUAGE/$READTHEDOCS_VERSION/\"" >> doc/book.toml
    - mdbook build doc --dest-dir=$READTHEDOCS_OUTPUT/html
    # List the output files
    - ls -lR $READTHEDOCS_OUTPUT/html
