[workspace]
value_file = "value.json"

[[action]]
name = "process_point"
command = "echo {directory}"
[action.group]
sort_by = ["/x"]
# ANCHOR: max
maximum_size = 4
# ANCHOR_END: max
[[action.group.include]]
condition = ["/type", "==", "point"]

[[action]]
name = "process_letter"
command = "echo {directory}"
[[action.group.include]]
condition = ["/type", "==", "letter"]
