[workspace]
value_file = "value.json"

[[action]]
name = "process_point"
command = "echo {directory}"
[action.group]
include = [["/type", "==", "point"]]
sort_by = ["/x"]
split_by_sort_key = true

[[action]]
name = "process_letter"
command = "echo {directory}"
[action.group]
include = [["/type", "==", "letter"]]
