[workspace]
value_file = "value.json"

[[action]]
name = "process_point"
command = "echo {directory}"
[action.group]
sort_by = ["/x"]
# ANCHOR: split
split_by_sort_key = true
# ANCHOR_END: split
[[action.group.include]]
condition = ["/type", "==", "point"]

[[action]]
name = "process_letter"
command = "echo {directory}"
[[action.group.include]]
condition = ["/type", "==", "letter"]
