blank_issues_enabled: true
contact_links:
  - name: Row discussion board
    url: https://github.com/glotzerlab/row/discussions/
    about: Ask the Row user community for help.
  - name: Row documentation
    url: https://row.readthedocs.io/
    about: User documentation.
