name: Feature request
description: Suggest a new **row** feature
labels: ['enhancement']
body:
  - type: textarea
    attributes:
      label: Description
      description: What new capability would you like in **row**?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: How should this capability be implemented? What might user interface look like?
  - type: textarea
    attributes:
      label: Additional context
      description: What additional information is helpful to understand this request?
  - type: markdown
    attributes:
      value: |
        We would welcome your contribution!

        If you plan to implement this functionality, the **row** developers will discuss the
        proposed design and API with you **before** you begin work.
