[book]
language = "en"
multilingual = false
src = "src"
title = "Row documentation"

[output.html]
git-repository-url = "https://github.com/glotzerlab/row"

[build]
create-missing = false

# Uncomment to enable link checking in docs. Normally these checks are only performed in CI.
# You also need to install https://github.com/Michael-F-Bryan/mdbook-linkcheck.
# [output.linkcheck]
# follow-web-links = true
