[book]
language = "en"
multilingual = false
src = "src"
title = "Row documentation"

[build]
create-missing = false

# [output.html] must be the last table so that .readthedocs.yaml can easily add a key to it
[output.html]
git-repository-url = "https://github.com/glotzerlab/row"
additional-css = ["rtd-mdbook.css"]
edit-url-template = "https://github.com/glotzerlab/row/edit/trunk/doc/{path}"
