name: pre-commit

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
    - "*"

  workflow_dispatch:

env:
  RUST_VERSION: 1.78.0

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.6
    # For unknown reasons, pre-commit fails with error: component download failed for cargo-x86_64-unknown-linux-gnu: could not rename downloaded file ...
    # unless we install with rustup first manually.
    - name: Update rust
      run: rustup install "$RUST_VERSION" --no-self-update && rustup default "${RUST_VERSION}"
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Install clippy
      run: rustup component add clippy
    - uses: actions/cache@v4.0.2
      with:
        path: |
          ~/.cache/pre-commit/
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
    - uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.12'
    - name: Install pre-commit
      run: pip install -r .github/workflows/pre-commit-requirements.txt
    - name: Run pre-commit
      run: pre-commit run --all-files
