name: pre-commit

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
    - "*"

  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.3
    - uses: actions/cache@v4.0.2
      with:
        path: |
          ~/.cache/pre-commit/
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.12'
    - run: pip install -r .github/workflows/pre-commit-requirements.txt
    - run: pre-commit run --all-files
