name: release

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

  push:
    branches:
    - trunk
    tags:
      - "*"

  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  name: row
  CARGO_TERM_COLOR: always
  CLICOLOR: 1
  RUST_VERSION: 1.80.0

jobs:
  source:
    name: Build source tarball
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        path: code

    - name: Determine filename-safe ref from GITHUB_REF_NAME
      run: echo ref="$(echo "${GITHUB_REF_NAME}" | sed  -e 's/\//-/g')" >> "$GITHUB_ENV"

    - name: Copy source
      run: cp -R code "${name}-${ref}"

    - name: Remove .git
      run: rm -rf "${name}-${ref}/.git" && ls -laR "${name}-${ref}"

    - name: Tar/zstd source
      run: tar --zstd -cvf "${name}-${ref}.tar.zst" "${name}-${ref}"

    - uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
      with:
        name: source
        path: |
          *.tar.*

  release-notes:
    name: Extract release notes
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        path: code

    - name: Write release-notes.md
      # 1. Search for the content from the start of the file to the 2nd version heading.
      # 2. Remove the 2nd version heading.
      # 3. Search for the content after the first version heading (removes any description at the
      #    start of the file.
      # 4. Remove the 1st version heading.
      # This leaves the content of the release notes for the current release.
      run: >
        grep -P -m 2 -B 10000 "^## v*\d*\.\d*\.\d*" doc/src/release-notes.md |
        sed '$d' |
        grep -P -A 10000 "^## v*\d*\.\d*\.\d*" |
        sed '1d' |
        tee "${GITHUB_WORKSPACE}/release-notes.md"
      working-directory: code

    - uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
      with:
        name: release-notes
        path: |
          release-notes.md

  binary:
    name: Build [${{ matrix.target }}]
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        target:
        - x86_64-unknown-linux-gnu
        - aarch64-apple-darwin
        include:
        - target: x86_64-unknown-linux-gnu
          runner: ubuntu-20.04
        - target: aarch64-apple-darwin
          runner: macos-14

    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Determine filename-safe ref from GITHUB_REF_NAME
      run: echo ref="$(echo "${GITHUB_REF_NAME}" | sed  -e 's/\//-/g')" >> "$GITHUB_ENV"
    - name: Update rust
      run: rustup install "$RUST_VERSION" --no-self-update && rustup default "$RUST_VERSION"
    - name: Check rust installation
      run: rustc -vV
    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-rust-${{ env.RUST_VERSION }}-cargo-release-binary-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --locked --bin "${name}" --release --target ${{ matrix.target }}
    - name: Check output
      run: file "target/${{ matrix.target }}/release/${name}"
    - name: Compress
      run: cp "target/${{ matrix.target }}/release/${name}" . && tar --zstd -cvf "${name}-${ref}-${{ matrix.target }}.tar.zst" "${name}"
    - uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
      with:
        name: ${{ matrix.target }}
        path: "${{ env.name }}-${{ env.ref }}-${{ matrix.target }}.tar.zst"

  publish_github:
    name: Publish [GitHub]
    needs: [binary, source, release-notes]
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        merge-multiple: true

    - name: List files
      run: ls -lR

    - name: Create release
      uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          *.zst
        body_path: release-notes.md
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_cargo:
    name: Publish [Cargo]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Update rust
      run: rustup install "$RUST_VERSION" --no-self-update && rustup default "$RUST_VERSION"
    - name: Check rust installation
      run: rustc -vV
    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-rust-${{ env.RUST_VERSION }}-cargo-publish-${{ hashFiles('**/Cargo.lock') }}
    - name: Dry run
      run: cargo publish --all-features --dry-run
    - name: Publish to crates.io
      if: startsWith(github.ref, 'refs/tags/')
      run: cargo publish --all-features --token ${{ secrets.CRATES_IO_API_TOKEN }}
