name: Style

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
    - trunk

  workflow_dispatch:

env:
  name: row
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:
  cargo-check:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Configure Rust
      uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
      with:
        toolchain: 1.94.0
    - name: Cache
      uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      with:
        cache-bin: false
    - run: cargo check --all-targets --all-features

  cargo-clippy:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Configure Rust
      uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
      with:
        toolchain: 1.94.0
        components: clippy
    - name: Cache
      uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      with:
        cache-bin: false
    - run: cargo clippy --all-targets --all-features -- -Dwarnings

  cargo-fmt:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Configure Rust
      uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
      with:
        toolchain: 1.94.0
        components: rustfmt
    - run: cargo fmt --check

  prek:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: prek
      uses: j178/prek-action@bdca6f102f98e2b4c7029491a53dfd366469e33d # v2.0.4
      with:
        prek-version: '0.3.8'

  # This job is used to provide a single requirement for branch merge conditions.
  tests_complete:
    name: All style checks
    if: always()
    needs: [cargo-check, cargo-clippy, cargo-fmt, prek]
    runs-on: ubuntu-24.04

    steps:
    - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
    - name: Done
      run: exit 0
