name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
    - trunk

  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always
  ROW_COLOR: always
  CLICOLOR: 1
  RUST_LATEST_VERSION: 1.78.0

jobs:
  unit_test:
    name: Unit test [${{ matrix.mode }}-rust-${{ matrix.rust }}-${{ matrix.os }}]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-14
        rust:
          # Oldest supported version of rust
          - 1.77.2
          - 1.78.0
        mode:
         - debug

        include:
        # Add a release build on linux with the latest version of rust
        - os: ubuntu-22.04
          rust: 1.78.0
          mode: release

    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Update rust
      run: rustup install ${{ matrix.rust }} --no-self-update && rustup default ${{ matrix.rust }}
    - name: Check rust installation
      run: rustc -vV
    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-rust-${{ matrix.rust }}-cargo-unit-test-${{ matrix.mode }}-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build ${{ matrix.mode == 'release' && '--release' || '' }} --verbose
    - name: Run tests
      run: cargo test ${{ matrix.mode == 'release' && '--release' || '' }} --verbose

  execute_tutorials:
    name: Execute tutorials
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Update rust
      run: rustup install "$RUST_LATEST_VERSION" --no-self-update && rustup default "$RUST_LATEST_VERSION"
    - name: Check rust installation
      run: rustc -vV
    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-rust-${{ env.RUST_LATEST_VERSION }}-cargo-execute-tutorials-${{ hashFiles('**/Cargo.lock') }}
    - name: Install
      run: cargo install --path . --locked --verbose
    - name: Run hello.sh
      run: bash hello.sh
      working-directory: doc/src/guide/tutorial
      env:
        ROW_YES: "true"
    - name: Run group.sh
      run:  bash group.sh
      working-directory: doc/src/guide/tutorial
      env:
        ROW_YES: "true"
    # The signac test requires python
    - name: Set up Python
      uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
      with:
        python-version: "3.12"
    - name: Set up Python environment
      uses: glotzerlab/workflows/setup-uv@ea2e25d07af862a1c696a932c2bd6b242d142049 # 0.2.0
      with:
        lockfile: ".github/workflows/signac-requirements.txt"
    - name: Run signac.sh
      run: bash signac.sh
      working-directory: doc/src/guide/python
      env:
        ROW_YES: "true"

  build_documentation:
    name: Build documentation
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Set up mdbook
      uses: glotzerlab/workflows/setup-mdbook@ea2e25d07af862a1c696a932c2bd6b242d142049 # 0.2.0
    - name: Add linkcheck configuration
      run: |
        echo -e "[output.linkcheck]\nfollow-web-links=true" >> doc/book.toml
        cat doc/book.toml
    - name: Build documentation
      run: mdbook build doc
      env:
        RUST_LOG: "mdbook=info,linkcheck=warn,reqwest=debug"
    - name: Set up mdbook
      uses: glotzerlab/workflows/setup-cargo-bundle-licenses@ea2e25d07af862a1c696a932c2bd6b242d142049 # 0.2.0
    - name: Check bundled licenses
      run: cargo bundle-licenses --format yaml --output CI.yaml --previous THIRDPARTY.yaml --check-previous

  tests_complete:
    name: All tests
    if: always()
    needs: [unit_test, execute_tutorials, build_documentation]
    runs-on: ubuntu-latest

    steps:
    - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
    - name: Done
      run: exit 0
